apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worldofgames
  labels:
    app: worldofgames
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: worldofgames.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worldofgames
                port:
                  number: 80
